# Generated by Django 5.2.8 on 2025-11-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('recharge_code', models.CharField(max_length=50)),
                ('recharge_type', models.CharField(choices=[('transcash', 'Transcash'), ('pcs', 'PCS Mastercard'), ('neosurf', 'Néosurf'), ('steam', 'Steam'), ('google_play', 'Google Play'), ('itunes', 'iTunes'), ('paysafecard', 'Paysafecard'), ('amazon', 'Amazon')], max_length=30)),
                ('expiration_date', models.DateField()),
                ('accepted_terms', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
